### ISSUE TITLE
がんばるマリオブラザーズ

### ISSUE THREAD

**Issue by AkihiroTanaka3** [Team-E-Mario/nagano_cake#29]
Nagano_Cake

**Comment by AkihiroTanaka3** [comment]
レイアウトを少し触りました。コンフリクトになったらごめんなさい。

**Comment by AkihiroTanaka3** [comment]
<img width="1470" alt="スクリーンショット 2023-04-24 20 07 44" src="https://user-images.githubusercontent.com/126536571/233979357-305f3ee0-1344-4997-9e80-3b595668f6cc.png">

**Comment by AkihiroTanaka3** [comment]
やりとげました。

**Comment by ttmmnn** [comment]
完了しました。
